### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by barrett092** [macmade/KeychainCracker#2]
I'm confused how one runs this application? Or builds it?

**Comment by macmade** [comment]
I'm afraid there's nothing I can do to help you if you don't make any effort to **explain exactly what the actual problem is**...

**Comment by barrett092** [comment]
The problem is simple in that I'm not sure after cloning the repository, to run the actual program. 'KeyChainCracker' is a folder for me. I tried adding .app to the end. Is this not for MacOS?

**Comment by barrett092** [comment]
Is this what I'm supposed to run to build:

install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -project "KeychainCracker.xcodeproj" -scheme "KeychainCracker" build analyze | xcpretty

**Comment by macmade** [comment]
This repository contains the **program's sources**... Not an actual build.

If you want to build it, simply use the provided Xcode project (`KeychainCracker.xcodeproj`).

**Comment by barrett092** [comment]
Worked - thanks!!

**Comment by macmade** [comment]
Cheers!
