### ISSUE TITLE
KeychainCracker.app

### ISSUE THREAD

**Issue by Bhlowe** [macmade/KeychainCracker#3]
Do you have a pre-built binary you could upload? You can create a github "release" and add a binary..
Looks interesting.. Trying to recover keychain from deceased friend for his wife.

**Comment by macmade** [comment]
No, sorry... Simply build it by yourself if you need it. Should be quite straightforward...

**Comment by n00py** [comment]
I made a release if anyone needs it but doesn't have the free HD space to install Xcode.   

https://github.com/n00py/KeychainCracker/releases
